@host = https://localhost:7000

### Valid Password
POST {{host}}/api/login HTTP/1.1
Content-Type: application/json
{
    "username": "john",
    "password": "password123"
}

### Invalid Password

POST {{host}}/api/login HTTP/1.1
Content-Type: application/json
{
    "username": "john",
    "password": "invalid_password"
}
