@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzU4MjkzMDUsIm5hbWUiOiJqb2huLmRvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiU21pdGgiLCJwaG9uZV9udW1iZXIiOiI1NTUtMTIzLTAwMCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6bnVsbCwiaWF0IjoxNzc1ODI1NzA1LCJuYmYiOjE3NzU4MjU3MDV9.rBceD6FxVVwZV9FjlnAgIx3Pbips5hwB3yJH5Udtsqo


GET https://localhost:7000/api/products
Authorization: Bearer eyJhbGciOiJodHRwOj8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJiIiwiaXNzIjoiYSIsImV4cCI6MTc3NTgzMDMwNCwibmFtZSI6ImpvaG4uZG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImdpdmVuX25hbWUiOiJKb2huIiwiZmFtaWx5X25hbWUiOiJTbWl0aCIsInBob25lX251bWJlciI6IjU1NS0xMjMtMDAwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpudWxsLCJpYXQiOjE3NzU4MjY3MDQsIm5iZiI6MTc3NTgyNjcwNH0.oaIf-B1HRF_Datp0zED4P-qnDGIHsIBKTIHEpUQjh8U
