

POST https://localhost:7000/api/cart/items HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "name": "Myszka",
  "price": 100
}

###

DELETE https://localhost:7000/api/cart/items/1 HTTP/1.1

###

POST https://localhost:7000/api/cart/checkout HTTP/1.1


### 
GET https://localhost:7286/hc




